from __future__ import annotations

from carbono_solo.collector.models import CATALOG_ONLY, InventoryRecord, SourceResult


def _record(
    source_id: str,
    source_name: str,
    dataset_id: str,
    title: str,
    url: str,
    country_scope: str,
    access_type: str,
    brazil_filter: str,
    candidate_target_fields: str,
    target_fit_score: str,
    implementation_status: str,
    license_name: str,
    notes: str,
    retrieved_at: str,
) -> InventoryRecord:
    return InventoryRecord(
        source_id=source_id,
        source_name=source_name,
        dataset_id=dataset_id,
        title=title,
        url=url,
        country_scope=country_scope,
        access_type=access_type,
        brazil_filter=brazil_filter,
        candidate_target_fields=candidate_target_fields,
        target_fit_score=target_fit_score,
        implementation_status=implementation_status,
        license=license_name,
        notes=notes,
        retrieved_at=retrieved_at,
    )


def collect_static_catalog(retrieved_at: str) -> SourceResult:
    inventory = [
        _record(
            "soildata",
            "SoilData",
            "soildata_repository",
            "SoilData Brazilian soil data repository",
            "https://www.pedometria.org/soildata/",
            "Brazil",
            "dataverse_search",
            "native_brazil_repository",
            "carbon, organic carbon, bulk density, layer depth, coarse fragments",
            "high",
            CATALOG_ONLY,
            "",
            "Repository-level catalog entry; detailed datasets are discovered through the Dataverse search adapter.",
            retrieved_at,
        ),
        _record(
            "febr",
            "FEBR",
            "febr_repository",
            "Repositorio Brasileiro Livre para Dados Abertos do Solo",
            "https://www.pedometria.org/febr/",
            "Brazil",
            "catalog",
            "native_brazil_repository",
            "carbon, soil properties, profile observations",
            "medium",
            CATALOG_ONLY,
            "",
            "Legacy Brazilian soil repository migrated toward SoilData; kept for traceability.",
            retrieved_at,
        ),
        _record(
            "bdsolos_embrapa",
            "SISolos / BD Solos Embrapa",
            "bdsolos_embrapa",
            "Sistema de Informacao de Solos Brasileiros",
            "https://www.bdsolos.cnptia.embrapa.br/",
            "Brazil",
            "web_application",
            "native_brazil_system",
            "soil profile and laboratory variables when public export is available",
            "high",
            CATALOG_ONLY,
            "",
            "Repository-level catalog entry; public organic carbon CSV export is ingested by the BD Solos adapter.",
            retrieved_at,
        ),
        _record(
            "wosis_brazil",
            "WoSIS Brazil subset",
            "wosis",
            "World Soil Information Service filtered to Brazil",
            "https://www.isric.org/explore/wosis",
            "Global",
            "external_download_or_api",
            "filter_points_inside_brazil",
            "organic carbon, total carbon, bulk density, coarse fragments, layer depth",
            "high",
            CATALOG_ONLY,
            "",
            "Global source; first implementation inventories it and reserves source priority for later Brazil-only ingestion.",
            retrieved_at,
        ),
        _record(
            "israd_brazil",
            "ISRaD Brazil subset",
            "israd",
            "International Soil Radiocarbon Database filtered to Brazil",
            "https://www.soilradiocarbon.org/database-1",
            "Global",
            "zip_csv_download",
            "filter_points_inside_brazil",
            "percent carbon, bulk density, layer depth, site coordinates",
            "medium",
            CATALOG_ONLY,
            "CC BY 4.0",
            "Global radiocarbon source; first implementation inventories it and reserves source priority for later Brazil-only ingestion.",
            retrieved_at,
        ),
        _record(
            "ibge_bdia",
            "BDiA / IBGE",
            "bdia_ibge",
            "Banco de Dados e Informacoes Ambientais",
            "https://bdiaweb.ibge.gov.br/",
            "Brazil",
            "catalog",
            "native_brazil_environmental_catalog",
            "soil classes and environmental context",
            "low",
            CATALOG_ONLY,
            "",
            "Useful for future covariates, not for target observations in this phase.",
            retrieved_at,
        ),
        _record(
            "radam_ibge",
            "RADAM / IBGE",
            "radam_ibge",
            "RADAMBRASIL soil and environmental survey references",
            "https://www.ibge.gov.br/",
            "Brazil",
            "document_or_map_catalog",
            "native_brazil_historical_reference",
            "soil classes and historical survey maps",
            "low",
            CATALOG_ONLY,
            "",
            "Useful as historical reference; PDF/OCR extraction is outside this phase.",
            retrieved_at,
        ),
        _record(
            "siga_go_solos_ibge",
            "SIGA-GO Solos - IBGE",
            "siga_dataset_423",
            "Solos - IBGE",
            "https://siga.meioambiente.go.gov.br/catalogue/#/dataset/423",
            "Brazil: Goias",
            "geonode_wfs",
            "native_goias_layer",
            "soil order, texture, horizon, relief, stoniness",
            "low",
            CATALOG_ONLY,
            "not_specified",
            "Pedological polygon layer for Goias; covariate candidate, not target observations.",
            retrieved_at,
        ),
    ]
    return SourceResult(inventory=inventory, targets=[])
